<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Admin-PC" name="com.automationpractice.qa.testcases.Testcases" tests="5" failures="1" timestamp="01 Sep 2019 16:48:35 GMT" time="54.741" errors="0">
  <testcase name="AutomationPractice_TC01" time="29.185" classname="com.automationpractice.qa.testcases.Testcases"/>
  <testcase name="AutomationPractice_TC02" time="2.443" classname="com.automationpractice.qa.testcases.Testcases"/>
  <testcase name="AutomationPractice_TC03" time="18.422" classname="com.automationpractice.qa.testcases.Testcases"/>
  <testcase name="AutomationPractice_TC04" time="3.585" classname="com.automationpractice.qa.testcases.Testcases"/>
  <testcase name="AutomationPractice_TC05" time="1.106" classname="com.automationpractice.qa.testcases.Testcases">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Invalid email address. expected [Invalid email address.] but found [123456]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Invalid email address. expected [Invalid email address.] but found [123456]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.automationpractice.qa.pages.AccountLoginPage.LoginFail(AccountLoginPage.java:98)
	at com.automationpractice.qa.testcases.Testcases.AutomationPractice_TC05(Testcases.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AutomationPractice_TC05 -->
</testsuite> <!-- com.automationpractice.qa.testcases.Testcases -->
